/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horoscope;

import static horoscope.numerology.num;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author my
 */
public class Sunsignguess extends javax.swing.JFrame {
static int sun,hor;
static String ss;
    /**
     * Creates new form armstrongnos
     */
    public Sunsignguess() {
        initComponents();
        jComboBox1.removeAllItems();
        for(int i=1970; i<=2025;i++)
        {
        jComboBox1.addItem(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(233, 84, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Kalam", 1, 56)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Let us know ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 350, 60));

        jLabel6.setFont(new java.awt.Font("Kalam", 1, 82)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("your Sunsign!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 560, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Kalam", 1, 18)); // NOI18N
        jButton1.setText("print your D.O.B");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 190, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Kalam", 1, 16)); // NOI18N
        jButton2.setText("know your sunsign");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 190, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Kalam", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 102, 102));
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 200, 70));

        jComboBox1.setBackground(new java.awt.Color(153, 153, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 80, 30));

        jLabel1.setFont(new java.awt.Font("Kalam", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setText(" year");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Kalam", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 204));
        jLabel3.setText(" month");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 120, 30));

        jComboBox2.setBackground(new java.awt.Color(153, 153, 255));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox2MousePressed(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 50, 30));

        jLabel4.setFont(new java.awt.Font("Kalam", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        jLabel4.setText(" date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, 30));

        jComboBox3.setBackground(new java.awt.Color(153, 153, 255));
        jComboBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 50, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Kalam", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 500, 60));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setForeground(new java.awt.Color(204, 255, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horoscope/pics/BGGUESS.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 800, 450));

        jToggleButton1.setBackground(new java.awt.Color(255, 204, 0));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton1.setText("EXIT");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, 50, 30));

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jButton4.setText("show horoscope");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 530, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox2.removeAllItems();
        for(int i=1; i<=12;i++)
        {
            jComboBox2.addItem(String.valueOf(i));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        jComboBox3.removeAllItems();
        int year = Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()));
        int month = Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));
        int ndays = 0;
        if(month==1||month==3||month==5||month==7||month==8||month==10||month==12)
        {
            ndays=31;
        }
        else if(month==4||month==6||month==9||month==11)
        {
            ndays=30;
        }
        else if(month==2)
        {
            if(year%4==0)
            {
                ndays=29;
            }
            else
            {ndays=28;}

        }
        /*JOptionPane.showMessageDialog(this,ndays);*/
        for(int i=1; i<=ndays;i++)
        {
            jComboBox3.addItem(String.valueOf(i));
        } 
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked

    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int y = Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()));
        int m = Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));
        int l = Integer.parseInt(String.valueOf(jComboBox3.getSelectedItem()));

        String h = String.valueOf(l+"/"+m+"/"+y);
        jTextField1.setText(h);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int year = Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()));
int month = Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));
int date = Integer.parseInt(String.valueOf(jComboBox3.getSelectedItem()));


if(year!=-1 && month!=-1 && date!=-1)
   {
    if((month==3 && date>=21)||(month==4 && date<=19))
        {
        jLabel7.setText("Your sunsign is ARIES.");
        ss="aries";
        }
    if((month==4 && date>=20)||(month==5 && date<=20))
        {
        jLabel7.setText("Your sunsign is TAURUS.");
        ss="taurus";
        }
    if((month==5 && date>=21)||(month==6 && date<=20))
        {
        jLabel7.setText("Your sunsign is GEMINI.");
        ss="gemini";
        }
    if((month==6 && date>=21)||(month==7 && date<=22))
        {
        jLabel7.setText("Your sunsign is CANCER.");
        ss="cancer";
        }
    if((month==7 && date>=23)||(month==8 && date<=22))
        {
        jLabel7.setText("Your sunsign is LEO.");
        ss="leo";
        }
    if((month==8 && date>=23)||(month==9 && date<=22))
        {
        jLabel7.setText("Your sunsign is VIRGO.");
        ss="virgo";
        }
    if((month==9 && date>=23)||(month==10 && date<=22))
        {
        jLabel7.setText("Your sunsign is LIBRA.");
        ss="libra";
        }
    if((month==10 && date>=23)||(month==11 && date<=21))
        {
        jLabel7.setText("Your sunsign is SCORPIO.");
        ss="scorpio";
        }
    if((month==11 && date>=22)||(month==12 && date<=21))
        {
        jLabel7.setText("Your sunsign is SAGITTARIUS.");
        ss="sagittarius";
        }
    if((month==12 && date>=22)||(month==1 && date<=19))
        {
        jLabel7.setText("Your sunsign is CAPRICORN.");
        ss="capricon";
        }
    if((month==1 && date>=20)||(month==2 && date<=18))
        {
        jLabel7.setText("Your sunsign is AQUARIUS.");
        ss="aquarius";
        }
    if((month==2 && date>=19)||(month==3 && date<=20))
        {
        jLabel7.setText("Your sunsign is PISCES.");
        ss="pisces";
        }
   sun = 200;
    try
        {
        Class.forName("java.sql.DriverManager");
        Connection x=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/kkpr19","root","a");
        Statement s =(Statement)x.createStatement();
        String query1 = "update payment set sunsign='"+sun+"' where username='"+login.username+"';";
        String query2 = "update login set sunsign='"+ss+"' where username='"+login.username+"';";
        s.executeUpdate(query1);
        s.executeUpdate(query2);
        }
    catch (Exception e)
        {
        JOptionPane.showMessageDialog(this,e.getMessage());
        } 
   
   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MousePressed
       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MousePressed

    private void jComboBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseEntered

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
new payment().setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int month = Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem()));
        int date = Integer.parseInt(String.valueOf(jComboBox3.getSelectedItem()));
        int b = String.valueOf(month).length();
        int c = String.valueOf(date).length();

        {
            if((month==3 && date>=21)||(month==4 && date<=19))
            {
                new aries().setVisible(true);
            }
            if((month==4 && date>=20)||(month==5 && date<=20))
            {
                new Taurus().setVisible(true);
            }
            if((month==5 && date>=21)||(month==6 && date<=20))
            {
                new geminii().setVisible(true);
            }
            if((month==6 && date>=21)||(month==7 && date<=22))
            {
                new cancer().setVisible(true);
            }
            if((month==7 && date>=23)||(month==8 && date<=22))
            {
                new Leo().setVisible(true);
            }
            if((month==8 && date>=23)||(month==9 && date<=22))
            {
                new virgo().setVisible(true);
            }
            if((month==9 && date>=23)||(month==10 && date<=22))
            {
                new Libra().setVisible(true);
            }
            if((month==10 && date>=23)||(month==11 && date<=21))
            {
                new scorpio().setVisible(true);
            }
            if((month==11 && date>=22)||(month==12 && date<=21))
            {
                new sagittarius().setVisible(true);
            }
            if((month==12 && date>=22)||(month==1 && date<=19))
            {
                new capricon().setVisible(true);
            }
            if((month==1 && date>=20)||(month==2 && date<=18))
            {
                new aquarius().setVisible(true);
            }
            if((month==2 && date>=19)||(month==3 && date<=20))
            {
                new pisces().setVisible(true);
            }
        
    hor = 500;
    try
        {
        Class.forName("java.sql.DriverManager");
        Connection z=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/kkpr19","root","a");
        Statement s =(Statement)z.createStatement();
        String my = "update payment set hor='"+hor+"' where username='"+login.username+"';"; 
        s.executeUpdate(my);
        }
    catch (Exception e)
        {
        JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sunsignguess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sunsignguess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sunsignguess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sunsignguess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sunsignguess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
